### PR TITLE
Added SMTP auth and Pushbullet note sending

### PR DESCRIPTION
**Pull request by rorpage**

### CODE REVIEW

**Comment by rllynch** [comment]
Looks great, thanks rorpage!

**Comment by rorpage** [comment]
You're welcome! Do you use Pushbullet?

**Comment by rllynch** [comment]
I had heard of it before, but didn't try it until your pull request.  So far it looks like an easy way to push notifications onto iOS/Android devices, certainly easier than email or SMS.  How do you like it?

**Comment by rorpage** [comment]
Oh, I love it! Lately they added the ability to send SMS messages through
their service (and then through your phone) so I hardly ever have to look
at my phone. Also, typing SMS messages is super easy on the computer.

I also have a Pebble watch so I get Pushbullet notifications on my wrist.

I have a Disney Parks web app/site that I work on daily that uses
Pushbullet to alert people of various things too (like attractions going
down and upcoming events they're taking part in).

You could say I'm a fan. :)

**Pull request merged**
